Content:
    - ${ROOT_DIR}/doc/content
    - ${MOOSE_DIR}/framework/doc/content
    - ${MOOSE_DIR}/modules/fluid_properties/doc/content
    - ${MOOSE_DIR}/modules/heat_conduction/doc/content
    - ${MOOSE_DIR}/modules/ray_tracing/doc/content
    - ${MOOSE_DIR}/modules/navier_stokes/doc/content
    - ${MOOSE_DIR}/modules/reactor/doc/content
Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: SubChannel
        repo: https://github.inl.gov/ncrc/subchannel
        menu:
            Getting Started:
                Installation: getting_started/installation.md
                Using SubChannel: getting_started/using_SubChannel.md
                User Notes: getting_started/user_notes.md
                SubChannel Theory: getting_started/subchannel_theory.md
            Documentation:
                SubChannel-only Syntax: syntax/subchannel_only.md
                Complete Code Syntax: syntax/index.md
            V&V:
                Verification & Validation: v&v/v&v-list.md
            Tutorial:
                Tutorial Slides: main/index.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove:
            framework: !include ${MOOSE_DIR}/framework/doc/remove.yml
    MooseDocs.extensions.common:
        shortcuts:
            framework: !include ${MOOSE_DIR}/framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include ${MOOSE_DIR}/framework/doc/acronyms.yml
    MooseDocs.extensions.bibtex:
        duplicate_warning: False
